<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.0">
  <POU Name="MAIN" Id="{9bd4f19a-aa2c-4df4-9196-0e1551730d4d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	MachineModule : Machine := (Name := 'Machine');
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MachineModule.CyclicLogic();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
